"""TipoCafe

Revision ID: 205b0d125f24
Revises: e42a5a0e2399
Create Date: 2021-09-23 13:05:41.719483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205b0d125f24'
down_revision = 'e42a5a0e2399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_coffe_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_coffe_type')
    # ### end Alembic commands ###
